language: python

python:
- "3.7"

install:
- pip install -r ./requirements.txt

script:
- coverage run --timid --source ./src -m py.test
- coverage report
- bandit -s B301,B403,B101 -r ./src/

after_success:
  coveralls
