language: python

python:
- "3.7"

install:
- pip install -r ./requirements.txt

script:
- coverage run --timid --source ./app -m py.test ./tests/unit
- coverage report
- bandit -s B301,B403 -r ./app/

after_success:
  coveralls
